context:
  version: "2.8.13"

package:
  name: preconstruct
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@preconstruct/cli/-/cli-${{ version }}.tgz
  sha256: cefbe4d829ee30b91c3110f39f26913b93a4a03febd079c108d6de7f43a31179

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - preconstruct --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Dev and build your code painlessly in monorepos
  homepage: https://github.com/preconstruct/preconstruct
  repository: https://github.com/preconstruct/preconstruct

extra:
  recipe-maintainers:
    - danielnachun
